### ISSUE TITLE
Recommended "undocumented" sources

### ISSUE THREAD

**Issue by p4yl0ad** [Ap3x/WALKWHISPER#1]
http://undocumented.ntinternals.net/ is kind of a shit source for undocumented structures / consts and function prototypes, 

You should take a look at 
- https://github.com/winsiderss/systeminformer/tree/master/phnt 
- https://github.com/processhacker/phnt

**Comment by Ap3x** [comment]
Hello @p4yl0ad, thank you for the recommendation. I have updated the README. Please check [16b8910](https://github.com/Ap3x/WALKWHISPER/commit/16b89101f41034b3a8186ccfd7fbb71fc9413490) commit for the update.
